/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "proto/message.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(aelf_Transaction, aelf_Transaction, 4)


PB_BIND(aelf_Address, aelf_Address, AUTO)


PB_BIND(aelf_TransferInput, aelf_TransferInput, AUTO)



