/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.8 at Tue Jun 20 13:56:26 2023. */

#include "message.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t aelf_Transaction_fields[8] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, aelf_Transaction, from, from, &aelf_Address_fields),
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , OTHER, aelf_Transaction, to, from, &aelf_Address_fields),
    PB_FIELD(  3, INT64   , SINGULAR, STATIC  , OTHER, aelf_Transaction, ref_block_number, to, 0),
    PB_FIELD(  4, BYTES   , SINGULAR, CALLBACK, OTHER, aelf_Transaction, ref_block_prefix, ref_block_number, 0),
    PB_FIELD(  5, STRING  , SINGULAR, CALLBACK, OTHER, aelf_Transaction, method_name, ref_block_prefix, 0),
    PB_FIELD(  6, BYTES   , SINGULAR, CALLBACK, OTHER, aelf_Transaction, params, method_name, 0),
    PB_FIELD(10000, BYTES   , SINGULAR, CALLBACK, OTHER, aelf_Transaction, signature, params, 0),
    PB_LAST_FIELD
};

const pb_field_t aelf_Address_fields[2] = {
    PB_FIELD(  1, BYTES   , SINGULAR, CALLBACK, FIRST, aelf_Address, value, value, 0),
    PB_LAST_FIELD
};

const pb_field_t aelf_TransferInput_fields[5] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, aelf_TransferInput, to, to, &aelf_Address_fields),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, aelf_TransferInput, symbol, to, 0),
    PB_FIELD(  3, INT64   , SINGULAR, STATIC  , OTHER, aelf_TransferInput, amount, symbol, 0),
    PB_FIELD(  4, STRING  , SINGULAR, CALLBACK, OTHER, aelf_TransferInput, memo, amount, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 *
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(aelf_Transaction, from) < 65536 && pb_membersize(aelf_Transaction, to) < 65536 && pb_membersize(aelf_TransferInput, to) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_aelf_Transaction_aelf_Address_aelf_TransferInput)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
#error Field descriptor for aelf_Transaction.signature is too large. Define PB_FIELD_16BIT to fix this.
#endif


/* @@protoc_insertion_point(eof) */
