# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aelf.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\naelf.proto\x12\x04\x61\x65lf\"\xb2\x01\n\x0bTransaction\x12\x1b\n\x04\x66rom\x18\x01 \x01(\x0b\x32\r.aelf.Address\x12\x19\n\x02to\x18\x02 \x01(\x0b\x32\r.aelf.Address\x12\x18\n\x10ref_block_number\x18\x03 \x01(\x03\x12\x18\n\x10ref_block_prefix\x18\x04 \x01(\x0c\x12\x13\n\x0bmethod_name\x18\x05 \x01(\t\x12\x0e\n\x06params\x18\x06 \x01(\x0c\x12\x12\n\tsignature\x18\x90N \x01(\x0c\"\x18\n\x07\x41\x64\x64ress\x12\r\n\x05value\x18\x01 \x01(\x0c\"X\n\rTransferInput\x12\x19\n\x02to\x18\x01 \x01(\x0b\x32\r.aelf.Address\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x03\x12\x0c\n\x04memo\x18\x04 \x01(\tb\x06proto3')



_TRANSACTION = DESCRIPTOR.message_types_by_name['Transaction']
_ADDRESS = DESCRIPTOR.message_types_by_name['Address']
_TRANSFERINPUT = DESCRIPTOR.message_types_by_name['TransferInput']
Transaction = _reflection.GeneratedProtocolMessageType('Transaction', (_message.Message,), {
  'DESCRIPTOR' : _TRANSACTION,
  '__module__' : 'aelf_pb2'
  # @@protoc_insertion_point(class_scope:aelf.Transaction)
  })
_sym_db.RegisterMessage(Transaction)

Address = _reflection.GeneratedProtocolMessageType('Address', (_message.Message,), {
  'DESCRIPTOR' : _ADDRESS,
  '__module__' : 'aelf_pb2'
  # @@protoc_insertion_point(class_scope:aelf.Address)
  })
_sym_db.RegisterMessage(Address)

TransferInput = _reflection.GeneratedProtocolMessageType('TransferInput', (_message.Message,), {
  'DESCRIPTOR' : _TRANSFERINPUT,
  '__module__' : 'aelf_pb2'
  # @@protoc_insertion_point(class_scope:aelf.TransferInput)
  })
_sym_db.RegisterMessage(TransferInput)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRANSACTION._serialized_start=21
  _TRANSACTION._serialized_end=199
  _ADDRESS._serialized_start=201
  _ADDRESS._serialized_end=225
  _TRANSFERINPUT._serialized_start=227
  _TRANSFERINPUT._serialized_end=315
# @@protoc_insertion_point(module_scope)
